<?php 

/**
 * @file
 * Installfile for uc_mbe4.
 *
 * Development sponsored by just make IT! GbR - http://www.justmakeit.de/
 */

/**
 * hook_uninstall
 */
function uc_mbe4_uninstall(){
  // Delete all uc_mbe4-variables.
  variable_del('uc_mbe4_url');
  variable_del('uc_mbe4_username');
  variable_del('uc_mbe4_password');
  variable_del('uc_mbe4_serviceid');
  variable_del('uc_mbe4_clientid');
  variable_del('uc_mbe4_contentclass');
  variable_del('uc_mbe4_extracharge');
}

