<?php

/**
 * @file
 * Process payments using mbe4 mobile payment.
 *
 * Development sponsored by just make IT! GbR - http://www.justmakeit.de/
 */

/**
 * Implements hook_init().
 */
function uc_mbe4_init() {
  module_load_include('inc', 'uc_mbe4', 'mbe4.class');
  drupal_add_css(drupal_get_path('module', 'uc_mbe4') . '/uc_mbe4.css');
}

/**
 * Implements hook_menu().
 */
function uc_mbe4_menu() {
  $items = array();
  // Callback-Pfad für Redirect von mbe4
  $items['cart/mbe4/complete'] = array(
    'page callback' => 'uc_mbe4_complete',
    'access callback' => 'uc_mbe4_complete_access',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Make sure anyone can complete their mbe4 orders.
 */
function uc_mbe4_complete_access() {
  return TRUE;
}

/**
 * Implements hook_payment_method().
 */
function uc_mbe4_payment_method() {
  global $base_path;
  $logo = '<img id="mbe4-logo" src="' . $base_path . drupal_get_path('module', 'uc_mbe4') . '/mbe4_logo_xs.png"/>';
  $gateways[] = array(
    'id' => 'mbe4',
    'name' => 'mbe4 mobile payment',
    'title' => '<span id="mbe4-title">' . t('mbe4 mobile payment') . '<br/><span id="mbe4-subtitle">' . t('Easy payment with your mobile') . '</span></span>',
    'review' => t('mbe4 mobile payment'),
    'callback' => 'uc_payment_method_mbe4',
    'checkout' => TRUE,
    'weight' => 1,
    'no_gateway' => TRUE,
  );
  return $gateways;
}
/**
 * Payment method declaration.
 */
function uc_payment_method_mbe4($op, &$arg1) {
  switch ($op) {
    case 'cart-details':
      $details = t('Easy mobile payment with mbe4. Just enter your Mobile-Number and enter the received TAN.');
      return $details;
    case 'cart-process':
      return;
    case 'settings':
      $form['uc_mbe4_username'] = array(
        '#type' => 'textfield',
        '#description' => t('Enter your mbe4 Username'),
        '#title' => t('mbe4 Username:'),
        '#default_value' => variable_get('uc_mbe4_username', ''),
        '#required' => TRUE,
      );
      $form['uc_mbe4_password'] = array(
        '#type' => 'textfield',
        '#description' => t('Enter your mbe4 Password'),
        '#title' => t('mbe4 Password:'),
        '#default_value' => variable_get('uc_mbe4_password', ''),
        '#required' => TRUE,
      );
      $form['uc_mbe4_clientid'] = array(
        '#type' => 'textfield',
        '#description' => t('Enter your mbe4 Client ID'),
        '#title' => t('mbe4 Client ID:'),
        '#default_value' => variable_get('uc_mbe4_clientid', ''),
        '#required' => TRUE,
      );
      $form['uc_mbe4_serviceid'] = array(
        '#type' => 'textfield',
        '#description' => t('Enter your mbe4 Service ID'),
        '#title' => t('mbe4 Service ID:'),
        '#default_value' => variable_get('uc_mbe4_serviceid', ''),
        '#required' => TRUE,
      );
      $form['uc_mbe4_contentclass'] = array(
        '#type' => 'textfield',
        '#description' => t('Enter your mbe4 Content Class'),
        '#title' => t('mbe4 Content Class:'),
        '#default_value' => variable_get('uc_mbe4_contentclass', ''),
        '#required' => TRUE,
      );
      $form['uc_mbe4_extracharge'] = array(
        '#type' => 'textfield',
        '#description' => t('Enter your Extra Charge in % without trailing %-Symbol. To disable, just enter 0.'),
        '#title' => t('mbe4 Extra Charge:'),
        '#default_value' => variable_get('uc_mbe4_extracharge', '0'),
        '#required' => TRUE,
      );
      $form['uc_mbe4_url'] = array(
        '#type' => 'textfield',
        '#description' => t('Enter the mbe4 URL'),
        '#title' => t('mbe4 URL:'),
        '#default_value' => variable_get('uc_mbe4_url', 'https://billing.mbe4.de/widget/singlepayment'),
        '#required' => TRUE,
      );
      $form['uc_mbe4_checkout_button'] = array(
        '#type' => 'textfield',
        '#title' => t('Order review submit button text'),
        '#description' => t('Provide mbe4 specific text for the submit button on the order review page.'),
        '#default_value' => variable_get('uc_2checkout_checkout_button', t('Submit Order')),
      );
      return $form;
  }
}

/**
 * Complete Checkout.
 */
function uc_mbe4_complete($cart_id = 0) {
  // Erstellung mbe4-Objekt.
  $mbe4obj = new Mbe4(variable_get('uc_mbe4_username', ''), variable_get('uc_mbe4_password', ''), variable_get('uc_mbe4_clientid', ''), variable_get('uc_mbe4_serviceid', ''), variable_get('uc_mbe4_url', ''));
  // Validierung der Parameter.
  $result = $mbe4obj->validate_transaction($_GET, variable_get('uc_mbe4_password', ''));
  // Ist die Transaktion gültig?.
  if ($mbe4obj->is_valid_responsecode($result)) {
    $comment = t('Paid by !type, mbe4 order #!order.');
    uc_payment_enter($order->order_id, 'mbe4', $order->order_total, 0, NULL, $comment);
    // Empty that cart.
    uc_order_save($order);
    // Add a comment to let sales team know this came in through the site.
    uc_order_comment_save($order->order_id, 0, t('Order created through website.'), 'admin');
    uc_cart_empty($cart_id);
    $output = uc_cart_complete_sale($order, variable_get('uc_new_customer_login', FALSE));
    $page = variable_get('uc_cart_checkout_complete_page', '');
    if (!empty($page)) {
      drupal_goto($page);
    }
  }
  else {
    watchdog('uc_mbe4_transaction', "mbe4 transaction failed: " . $mbe4obj->get_responsemsg_by_responsecode($result));
    drupal_set_message('mbe4 transaction failed!', 'error');
    drupal_goto('cart/checkout/review');
    return $output;
  }
}

/**
 * Implements hook_form_alter().
 */
function uc_mbe4_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'uc_cart_checkout_review_form' && ($order_id = intval($_SESSION['cart_order'])) > 0) {
    $order = uc_order_load($order_id);
    if ($order->payment_method == 'mbe4') {
      unset($form['submit']);
      $form['#prefix'] = '<table id="two-checkout-review-table"><tr><td>';
      $form['#suffix'] = '</td><td>' . drupal_get_form('uc_mbe4_form', $order) . '</td></tr></table>';
    }
  }
}

/**
 *	Formular für Payment-Redirect erstellen. Wird von hook_form_alter aufgerufen
 *	und integriert die Formularfelder in das Review-Checkout-Formular.
 *	@return:
 *		Komplettes Redirect-Formular mit Key/Value-Array.
 */
function uc_mbe4_form($form_state, $order) {
  // mbe4-Objekt erstellen.
  $mbe4obj = new Mbe4(variable_get('uc_mbe4_username', ''), variable_get('uc_mbe4_password', ''), variable_get('uc_mbe4_clientid', ''), variable_get('uc_mbe4_serviceid', ''), variable_get('uc_mbe4_url', ''));
  // Beschreibung für die Transaktion vorbereiten.
  $description = t('Order @order_number at @store', array('@order_number' => $order->order_id, '@store' => variable_get('site_name', url('<front>', array('absolute' => TRUE)))));
  // Transaktion vorbereiten.
  $data = $mbe4obj->create_transaction(
      $order->order_id,
      $description,
      $order->order_total * 100,
      variable_get('uc_mbe4_contentclass', '1'),
      url('cart/mbe4/complete/' . uc_cart_get_id(), array('absolute' => TRUE)),
      TRUE
      );
  // Formular erstellen.
  $form['#action'] = variable_get('uc_mbe4_url', '');
  $form['#method'] = 'get';
  // $data-Array als Formularfelder hinzufügen.
  foreach ($data as $name => $value) {
    $form[$name] = array('#type' => 'hidden', '#value' => $value);
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => variable_get('uc_mbe4_checkout_button', t('Submit Order')),
  );
  // Formular zurück geben.
  return $form;
}

/**
 * hook_uninstall
 */
function uc_mbe4_uninstall(){
  // Delete all uc_mbe4-variables.
  variable_del('uc_mbe4_url');
  variable_del('uc_mbe4_username');
  variable_del('uc_mbe4_password');
  variable_del('uc_mbe4_serviceid');
  variable_del('uc_mbe4_clientid');
  variable_del('uc_mbe4_contentclass');
  variable_del('uc_mbe4_extracharge');
}
